In [1]:
import numpy as np

array1 = np.array([1,2,3,4,5])

In [4]:
array2 = np.array([1,2,3,4,5])
array2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
# Identity Matrix
np.eye(5).ndim

2

In [12]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition: ",arr1+arr2)
print("Sub: ",arr1-arr2)

Addition:  [11 22 33 44 55]
Sub:  [ -9 -18 -27 -36 -45]


In [13]:
arr3 = np.array([2,3,4,5,6])
print(np.sqrt(arr3))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [14]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr[0:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [27]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data > 5]

array([ 6,  7,  8,  9, 10])